version: '3'

networks:
  backend:
    driver: bridge

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ${CODE_DIR}:/var/www
      - ./nginx/sites:/etc/nginx/conf.d
    networks:
      - backend

  php-fpm-56:
    build: ./php-fpm-56
    volumes:
      - ${CODE_DIR}:/var/www
    networks:
      - backend

  php-fpm-80:
    build: ./php-fpm-80
    volumes:
      - ${CODE_DIR}:/var/www
    networks:
      - backend

  php-fpm-82:
    build: ./php-fpm-82
    ports:
      - "9501:9501"
      - "9082:9003"
    volumes:
      - ${CODE_DIR}:/var/www
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  mailpit:
    build: ./mailpit
    ports:
      - "${MAILPIT_WEB_PORT}:8025"
    networks:
      - backend
